service:
  type: LoadBalancer
  port: 5601

resources:
  requests:
    cpu: "200m"
    memory: "200Mi"
  limits:
    cpu: "1000m"
    memory: "2Gi"
podAnnotations:
  sidecar.istio.io/inject: "false"

